data:
  path_to_data: data                          # Local path where the train and validation data should be placed
                                              # in order to run the model training
  train_filename: toy_train.csv               # Filename of the training data
  text_field_name: title
  label_field_name: sentiment
  num_classes: 3
  max_text_length_words: 500
  class_names: ["Negative", "Neutral", "Positive"]

cross_val_params:                             # Params of cross-validation
  type: sklearn.model_selection.cross_val_score
  n_jobs: 4
  scoring: accuracy                           # Scoring name compatible with Sklearn
  cv:
    type: sklearn.model_selection.StratifiedKFold
    n_splits: 5
    shuffle: true
    random_state: 17

model_tfidf:
  type: sklearn.feature_extraction.text.TfidfVectorizer
  stop_words: english
  ngram_range: [1, 5]
  analyzer: char
  min_df: 8
  lowercase: true
  max_features: 100000

model_logreg:
  type: sklearn.linear_model.LogisticRegression
  C: 2.7
  solver: lbfgs
  multi_class: multinomial
  random_state: 17
  max_iter: 500
  n_jobs: 4
  fit_intercept: false

model_pipeline:
  type: sklearn.pipeline.Pipeline

model_engine:
  type: cryptonews_sentiment_analysis_app.model.engine.TfidfLogisticRegression
  model: model_pipeline
  class_names: ["Negative", "Neutral", "Positive"]
  round_up_to: 4
  path_to_model: models/logit_tfidf_btc_sentiment.pkl
  name: "Tf-Idf & logreg"
  version: "0.1.0"

# Hydra logging boilerplate
defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:  
  output_subdir: null  
  run:  
    dir: .
