version: 1
formatters:
  app:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: app
    stream: ext://sys.stdout
loggers:
  appLogger:
    level: INFO
    handlers: [console]
    propagate: no
root:
  level: INFO
  handlers: [console]