data:
  path_to_data: data                          # Local path where the train and validation data should be placed
                                              # in order to run the model training
  train_filename: toy_train.csv               # Filename of the training data
  text_field_name: title
  label_field_name: sentiment
  num_classes: 3
  max_text_length_words: 500
  class_names: ["Negative", "Neutral", "Positive"]

# Hydra logging boilerplate
defaults:
  - _self_
  - model: bert
  - logger: base
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .
