name: model_service
dependencies:
- nvidia::cudatoolkit=11.3.1
- numpy=1.21.2
- pillow=8.4.0
- pip=21.2.4
- python=3.9.7
- pytorch::pytorch=1.10.0=py3.9_cuda11.3_cudnn8.2.0_0
- scipy=1.7.1
- pytorch::torchvision=0.11.1=py39_cu113
- tqdm=4.62.3
- pip:
  - black[jupyter]==22.3.0
  - flake8==4.0.1
  - mypy==0.942
  - pre-commit==2.17.0
  - isort==5.10.1
  - transformers==4.18.0
  - datasets==2.0.0
  - scikit-learn==1.0.2
  - pytorch-lightning==1.6.0
  - hydra-core==1.1.2
  - fastapi==0.75.2
  - uvicorn==0.17.6
  - pydantic==1.9.0
  - mmh3==3.0.0